---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test-github-controller
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    testController:
      owner: arztz
      repository: argo-test-events
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://test-eventsource-github.nize.ai
      events:  
        - "*"
      apiToken:
        name: github-arztz-access
        key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-arztz-access
type: Opaque
data:
  token: NzA0YjI2MDBjNmY1MjlkNGY4MzBmOTY4MmMxMDVmZDZmYWU0M2I3Ywo=
