apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  template:
    spec:
      containers:
      - name: rollouts-demo
        image: asia.gcr.io/devops-sandbox-291905/arztz-test-argo-rollout:1.1.86 